//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelpaEntity : DbContext
    {
        public HelpaEntity()
            : base("name=HelpaEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<StaticPage> StaticPages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<Carousel> Carousels { get; set; }
        public virtual DbSet<JobLocation> JobLocations { get; set; }
        public virtual DbSet<Location1> Locations1 { get; set; }
        public virtual DbSet<Favourate> Favourates { get; set; }
        public virtual DbSet<ReviewAndRating> ReviewAndRatings { get; set; }
        public virtual DbSet<ReviewComment> ReviewComments { get; set; }
        public virtual DbSet<HelperService> HelperServices { get; set; }
        public virtual DbSet<HelperServiceScope> HelperServiceScopes { get; set; }
        public virtual DbSet<Scope> Scopes { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Helper> Helpers { get; set; }
        public virtual DbSet<JobPrice> JobPrices { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobScope> JobScopes { get; set; }
        public virtual DbSet<JobService> JobServices { get; set; }
        public virtual DbSet<JobTime> JobTimes { get; set; }
        public virtual DbSet<Reciever> Recievers { get; set; }
    }
}
