//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobService()
        {
            this.JobScopes = new HashSet<JobScope>();
        }
    
        public int JobServiceId { get; set; }
        public int JobId { get; set; }
        public int ServiceId { get; set; }
        public string RowStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobScope> JobScopes { get; set; }
    }
}
