//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobScope
    {
        public int JobScopeId { get; set; }
        public int JobServiceId { get; set; }
        public int ScopeId { get; set; }
        public string RowStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Scope Scope { get; set; }
        public virtual JobService JobService { get; set; }
    }
}
