//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationId { get; set; }
        public int SenderId { get; set; }
        public int ReceiverId { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string RowStatus { get; set; }
        public string NotificationState { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public string NotificationType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
